/*
 Navicat Premium Data Transfer

 Source Server         : 测试环境oracl
 Source Server Type    : Oracle
 Source Server Version : 120200
 Source Host           : 172.21.84.1:1521
 Source Schema         : C##TEST_ZNTB

 Target Server Type    : Oracle
 Target Server Version : 120200
 File Encoding         : 65001

 Date: 24/05/2024 15:05:25
*/


-- ----------------------------
-- Table structure for TA_ZNTB_INFO_ITEM_INST_RELA
-- ----------------------------
DROP TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA";
CREATE TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" (
  "LINK_ID" VARCHAR2(100 BYTE) VISIBLE NOT NULL ,
  "ITEM_GROUP_CODE" VARCHAR2(100 BYTE) VISIBLE ,
  "ITEM_GROUP_ID" VARCHAR2(100 BYTE) VISIBLE ,
  "INFORMATION_ITEM_NAME" VARCHAR2(4000 BYTE) VISIBLE NOT NULL ,
  "INFORMATION_ITEM_ID" VARCHAR2(4000 BYTE) VISIBLE ,
  "INFORMATION_ITEM_CODE" VARCHAR2(1000 BYTE) VISIBLE NOT NULL ,
  "RELA_TYPE" VARCHAR2(10 BYTE) VISIBLE ,
  "RELA" CLOB VISIBLE ,
  "RELA_DESCRIBE" VARCHAR2(4000 BYTE) VISIBLE ,
  "RELA_ORDER" VARCHAR2(100 BYTE) VISIBLE ,
  "STATE" VARCHAR2(10 BYTE) VISIBLE NOT NULL ,
  "CREATE_DATE" DATE VISIBLE DEFAULT sysdate  NOT NULL ,
  "UPDATE_DATE" DATE VISIBLE ,
  "CREATE_USER" VARCHAR2(100 BYTE) VISIBLE ,
  "CREATE_USER_ID" VARCHAR2(100 BYTE) VISIBLE ,
  "UPDATE_USER" VARCHAR2(100 BYTE) VISIBLE ,
  "UPDATE_USER_ID" VARCHAR2(100 BYTE) VISIBLE ,
  "IS_DELETE" VARCHAR2(100 BYTE) VISIBLE DEFAULT 'N' ,
  "EXPRESSION" VARCHAR2(4000 BYTE) VISIBLE ,
  "CHILD_ITEM_GROUP_CODE" VARCHAR2(50 BYTE) VISIBLE ,
  "API_TYPE" VARCHAR2(100 BYTE) VISIBLE ,
  "API_TYPE_ID" VARCHAR2(100 BYTE) VISIBLE ,
  "API_ID" VARCHAR2(100 BYTE) VISIBLE ,
  "API_DESCRIBE" VARCHAR2(500 BYTE) VISIBLE ,
  "API_REQUEST_PARAMETER" CLOB VISIBLE ,
  "API_RETURN_VALUE" CLOB VISIBLE ,
  "TYPE" VARCHAR2(100 BYTE) VISIBLE ,
  "FORMID" VARCHAR2(100 BYTE) VISIBLE ,
  "API_NAME" VARCHAR2(100 BYTE) VISIBLE ,
  "TEMPLATE_ID" VARCHAR2(50 BYTE) VISIBLE 
)
TABLESPACE "C##TEST_ZNTB"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA"."TEMPLATE_ID" IS '模板表单ID';

-- ----------------------------
-- Primary Key structure for table TA_ZNTB_INFO_ITEM_INST_RELA
-- ----------------------------
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0026646" PRIMARY KEY ("LINK_ID");

-- ----------------------------
-- Checks structure for table TA_ZNTB_INFO_ITEM_INST_RELA
-- ----------------------------
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0013321" CHECK ("LINK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0013322" CHECK ("INFORMATION_ITEM_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0013323" CHECK ("INFORMATION_ITEM_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0013324" CHECK ("STATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##TEST_ZNTB"."TA_ZNTB_INFO_ITEM_INST_RELA" ADD CONSTRAINT "SYS_C0013325" CHECK ("CREATE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
